-- MySQL Script generated by MySQL Workbench
-- 06/21/17 22:21:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema oscar_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oscar_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oscar_app` DEFAULT CHARACTER SET utf8 ;
USE `oscar_app` ;

-- -----------------------------------------------------
-- Table `oscar_app`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oscar_app`.`usuario` (
  `usuario` INT(11) NOT NULL,
  `nome` TEXT NULL DEFAULT NULL,
  `senha` TEXT NULL DEFAULT NULL,
  `voto_filme` TEXT NULL DEFAULT NULL,
  `voto_diretor` TEXT NULL DEFAULT NULL,
  `votou` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
